In [1]:
import numpy as np

In [75]:
x = np.random.random(10)
x

array([ 0.861164  ,  0.02394811,  0.03678956,  0.38151836,  0.62994522,
        0.87723164,  0.18728555,  0.22636271,  0.6821967 ,  0.55017748])

In [76]:
np.argsort(x)

array([1, 2, 6, 7, 3, 9, 4, 8, 0, 5])

In [63]:
np.min(x)

0.044965388107869209

In [64]:
np.argmin(x)

1

In [71]:
x.shape[0]

10

In [72]:
k_min_index=[]
Ypred = []
for j in range(x.shape[0]):
                min_index = np.argmin(x)
                print(min_index)
                k_min_index.append(min_index) #get the index with smallest distance
                Ypred.append(x[min_index])
                print(x[min_index])
                print(k_min_index)
                print(Ypred)#predict the label of the nearest example
                x=np.delete(x,min_index)
                print(x)

1
0.0101766678407
[1]
[0.010176667840737896]
[ 0.71204352  0.98481488  0.32697528  0.09158916  0.74725533  0.29325539
  0.61711382  0.70516534  0.67418361]
3
0.0915891631389
[1, 3]
[0.010176667840737896, 0.0915891631388841]
[ 0.71204352  0.98481488  0.32697528  0.74725533  0.29325539  0.61711382
  0.70516534  0.67418361]
4
0.293255387084
[1, 3, 4]
[0.010176667840737896, 0.0915891631388841, 0.29325538708392018]
[ 0.71204352  0.98481488  0.32697528  0.74725533  0.61711382  0.70516534
  0.67418361]
2
0.326975283299
[1, 3, 4, 2]
[0.010176667840737896, 0.0915891631388841, 0.29325538708392018, 0.3269752832994155]
[ 0.71204352  0.98481488  0.74725533  0.61711382  0.70516534  0.67418361]
3
0.617113815432
[1, 3, 4, 2, 3]
[0.010176667840737896, 0.0915891631388841, 0.29325538708392018, 0.3269752832994155, 0.61711381543238308]
[ 0.71204352  0.98481488  0.74725533  0.70516534  0.67418361]
4
0.67418361188
[1, 3, 4, 2, 3, 4]
[0.010176667840737896, 0.0915891631388841, 0.29325538708392018, 0.3269752832

In [52]:
x

array([ 0.8287895 ,  0.01460705,  0.54278342])

In [53]:
np.delete(x,2)

array([ 0.8287895 ,  0.01460705])

In [25]:
x = [ 0.54798674,  0.49126747,  0.92640559]

In [26]:
i = np.argmin(x)
i

1

In [27]:
x

[0.54798674, 0.49126747, 0.92640559]

In [28]:
del x[i]
x

[0.54798674, 0.92640559]

In [35]:
for i in range(2):
    print(i)
    

0
1


In [41]:
k_min_index = []

In [42]:
k_min_index.append(i)

In [44]:
k_min_index.append(17)
k_min_index

[1, 3, 17]

In [45]:
Ypred = [1,3,3]

In [46]:
from collections import Counter

In [47]:
Counter(Ypred)

Counter({1: 1, 3: 2})

In [50]:
Counter(Ypred).most_common(1)[0][0]

3